name: Validate Category Json

on:
  workflow_dispatch:
  push:
    paths:
    - "storage/"

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /schemas/category.json
          INPUT_JSONS: /storage/alphabet.json,/storage/animals.json,/storage/blocks.json,/storage/decoration.json,/storage/food-drinks.json,/storage/humanoid.json,/storage/humans.json,/storage/miscellaneous.json,/storage/monsters.json,/storage/plants.json
