name: Auto Updater
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight.
    
jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3.0.2
        with:
          token: ${{ secrets.RW }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Run
        run: java -jar target/HeadStorage.jar

      - name: Push Update
        run: |
          git config --global user.name 'AutoUpdater'
          git config --global user.email 'thesilentpro@users.noreply.github.com'
          git rm -r storage
          git rm -r ids.json
          git add storage
          git add ids.json
          git commit -m 'Auto-Push Updates'
          git push https://${{ secrets.RW }}@github.com/TheSilentPro/HeadStorage.git
